[project]
name = "taipy-financial-planning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "taipy>=4.1.0",
]
